### ISSUE TITLE
add support for gestures

### ISSUE THREAD

**Issue by petar** [gov4git/sample-project#1]

**Comment by gov4git-dao** [comment]
## <a href="https://gov4git.org"><img src="https://raw.githubusercontent.com/gov4git/gov4git/main/materials/gov4git-avatar.png" alt="This project is governed with Gov4Git." width="65" /></a> Gov4Git notices
On `Monday, 15-Jan-24 20:08:22 UTC` by Gov4Git `dev`

### Notice `zq7fqq`
Started managing this issue as Gov4Git concern `1` with initial __priority score__ of `0.000000`.

This project is managed by [Gov4Git](https://gov4git.org), a decentralized governance system for collaborative git projects.
To participate in governance, __install the [Gov4Git desktop app](https://github.com/gov4git/desktop-application)__.

**Comment by gov4git-dao** [comment]
## <a href="https://gov4git.org"><img src="https://raw.githubusercontent.com/gov4git/gov4git/main/materials/gov4git-avatar.png" alt="This project is governed with Gov4Git." width="65" /></a> Gov4Git notices
On `Monday, 15-Jan-24 21:31:43 UTC` by Gov4Git `dev`

### Notice `pc3k77`
This issue was referenced by https://github.com/gov4git/sample-project/pull/4, managed as Gov4Git proposal `4`.

**Comment by gov4git-dao** [comment]
## <a href="https://gov4git.org"><img src="https://raw.githubusercontent.com/gov4git/gov4git/main/materials/gov4git-avatar.png" alt="This project is governed with Gov4Git." width="65" /></a> Gov4Git notices
On `Monday, 15-Jan-24 21:33:50 UTC` by Gov4Git `dev`

### Notice `zllc5g`
This issue's __priority score__ was updated to `3.162278`.

### Notice `cxlihu`
The set of eligible proposals addressing this issue changed to:
- https://github.com/gov4git/sample-project/pull/4, managed as Gov4Git motion `4` with community attention of `3.162278`


### Notice `tslw6z`
Freezing ❄️ this issue as there are eligible PRs addressing it:
- https://github.com/gov4git/sample-project/pull/4

**Comment by gov4git-dao** [comment]
## <a href="https://gov4git.org"><img src="https://raw.githubusercontent.com/gov4git/gov4git/main/materials/gov4git-avatar.png" alt="This project is governed with Gov4Git." width="65" /></a> Gov4Git notices
On `Monday, 15-Jan-24 21:45:12 UTC` by Gov4Git `dev`

### Notice `qb5egd`
This issue, managed as Gov4Git proposal `1`, has been closed 🎉

The issue priority tally was `3.162278`.

Ths issue was resolved by [PR #4](https://github.com/gov4git/sample-project/pull/4):

Tally breakdown by user:
- User @petar contributed `3.162278` votes


### Notice `pshum4`
Gov4Git closed this issue, as the corresponding governance motion `1` has now been closed.
