### ISSUE TITLE
issue welcome bonus to new member

### ISSUE THREAD

**Issue by petar** [gov4git/sample-project#3]
issue 3000 credits to @petar

**Comment by gov4git-dao** [comment]
## <a href="https://gov4git.org"><img src="https://raw.githubusercontent.com/gov4git/gov4git/main/materials/gov4git-avatar.png" alt="This project is governed with Gov4Git." width="65" /></a> Follow up
On `Monday, 15-Jan-24 20:19:03 UTC` by Gov4Git `dev`

Issued `3000` credits to member @petar.
