### ISSUE TITLE
issue 3000 credits to @petar

### ISSUE THREAD

**Issue by petar** [gov4git/sample-project#7]
issue 3000 credits to @petar

**Comment by gov4git-dao** [comment]
## <a href="https://gov4git.org"><img src="https://raw.githubusercontent.com/gov4git/gov4git/main/materials/gov4git-avatar.png" alt="This project is governed with Gov4Git." width="65" /></a> Follow up
On `Monday, 05-Feb-24 17:00:10 UTC` by Gov4Git `dev`

Issued `3000` credits to member @petar.

**Comment by gov4git-dao** [comment]
## <a href="https://gov4git.org"><img src="https://raw.githubusercontent.com/gov4git/gov4git/main/materials/gov4git-avatar.png" alt="This project is governed with Gov4Git." width="65" /></a> Follow up
On `Monday, 05-Feb-24 17:57:47 UTC` by Gov4Git `dev`

Issued `3000` credits to member @petar.

**Comment by gov4git-dao** [comment]
## <a href="https://gov4git.org"><img src="https://raw.githubusercontent.com/gov4git/gov4git/main/materials/gov4git-avatar.png" alt="This project is governed with Gov4Git." width="65" /></a> Follow up
On `Monday, 05-Feb-24 19:02:52 UTC` by Gov4Git `dev`

Issued `3000` credits to member @petar.
