### ISSUE TITLE
put in the matching fund

### ISSUE THREAD

**Issue by petar** [gov4git/sample-project#9]
give 1000 credits to matching fund

**Comment by gov4git-dao** [comment]
## <a href="https://gov4git.org"><img src="https://raw.githubusercontent.com/gov4git/gov4git/main/materials/gov4git-avatar.png" alt="This project is governed with Gov4Git." width="65" /></a> Follow up
On `Monday, 05-Feb-24 17:03:45 UTC` by Gov4Git `dev`

Transferred `1000` credits from member @petar to member @pmp+matching.

**Comment by gov4git-dao** [comment]
## <a href="https://gov4git.org"><img src="https://raw.githubusercontent.com/gov4git/gov4git/main/materials/gov4git-avatar.png" alt="This project is governed with Gov4Git." width="65" /></a> Follow up
On `Monday, 05-Feb-24 19:04:14 UTC` by Gov4Git `dev`

Transferred `1000` credits from member @petar to the matching fund.
